version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - my-network
  
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app 
      - /usr/src/app/node_modules 
    networks:
      - my-network
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: